/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VocabularyRouteImport } from "./routes/vocabulary";
import { Route as FlashcardsRouteImport } from "./routes/flashcards";
import { Route as IndexRouteImport } from "./routes/index";

const VocabularyRoute = VocabularyRouteImport.update({
  id: "/vocabulary",
  path: "/vocabulary",
  getParentRoute: () => rootRouteImport,
} as any);
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: "/flashcards",
  path: "/flashcards",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/vocabulary": typeof VocabularyRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/vocabulary": typeof VocabularyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/flashcards": typeof FlashcardsRoute;
  "/vocabulary": typeof VocabularyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/flashcards" | "/vocabulary";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/flashcards" | "/vocabulary";
  id: "__root__" | "/" | "/flashcards" | "/vocabulary";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FlashcardsRoute: typeof FlashcardsRoute;
  VocabularyRoute: typeof VocabularyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vocabulary": {
      id: "/vocabulary";
      path: "/vocabulary";
      fullPath: "/vocabulary";
      preLoaderRoute: typeof VocabularyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/flashcards": {
      id: "/flashcards";
      path: "/flashcards";
      fullPath: "/flashcards";
      preLoaderRoute: typeof FlashcardsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  VocabularyRoute: VocabularyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
